# Geolocation using Nominatim
We'll import Nominatim from GeoPy and also a library that handles a large number of queries. The idea is to read the CSV of Lisbon, collect the coordinates, and add columns for these locations.

In [40]:
%config IPCompleter.greedy=True #autocomplete

!["Documentação GeoPy: Uso de Rate Limiter"](Snipaste_2025-07-07_08-09-03.png)

In [41]:
import geopy.geocoders
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter
import pandas as pd
import ssl
import certifi

Initializing the library with a localizer variable from which we'll apply functions, and reading the table, transforming it into a DataFrame.

In [42]:
ctx = ssl.create_default_context(cafile=certifi.where())
geopy.geocoders.options.default_ssl_context = ctx
ctx = ssl.create_default_context()
ctx.check_hostname = False
ctx.verify_mode = ssl.CERT_NONE

localizer = Nominatim(scheme = 'http', user_agent="my_geolocation_bars", timeout=10)
geocode = RateLimiter(localizer.geocode, min_delay_seconds=1)

df = pd.read_csv('lisbon_places_normalized.csv')
df

,name,category,partial_address,ref,website
0,TRUMPS,nightclub/bar,"TRUMPS, Lisboa - Portugal",https://www.lisbongaycircuit.com/#,NaN
1,FINALMENTE CLUBE,nightclub/bar,"FINALMENTE CLUBE, Lisboa - Portugal",https://www.lisbongaycircuit.com/#,NaN
2,CONSTRUCTION,nightclub/bar,"CONSTRUCTION, Lisboa - Portugal",https://www.lisbongaycircuit.com/#,NaN
3,PRESTIGE,nightclub/bar,"PRESTIGE, Lisboa - Portugal",https://www.lisbongaycircuit.com/#,NaN
4,106,nightclub/bar,"106, Lisboa - Portugal",https://www.lisbongaycircuit.com/#,NaN
5,BAR CRU,nightclub/bar,"BAR CRU, Lisboa - Portugal",https://www.lisbongaycircuit.com/#,NaN
6,CONSTRUCTION BAR - BAIRRO ALTO,nightclub/bar,"CONSTRUCTION BAR – BAIRRO ALTO, Lisboa - Portugal",https://www.lisbongaycircuit.com/#,NaN
7,ENTRETANTO ROOFTOP,nightclub/bar,"ENTRETANTO ROOFTOP, Lisboa - Portugal",https://www.lisbongaycircuit.com/#,NaN
8,TR3S,nightclub/bar,"TR3S, Lisboa - Portugal",https://www.lisbongaycircuit.com/#,NaN
9,SHELTER BAR,nightclub/bar,"SHELTER BAR, Lisboa - Portugal",https://www.lisbongaycircuit.com/#,NaN
10,SIDE BAR,nightclub/bar,"SIDE BAR, Lisboa - Portugal",https://www.lisbongaycircuit.com/#,NaN
11,MINIGOLF LISBON,nightclub/bar,"MINIGOLF LISBON, Lisboa - Portugal",https://www.lisbongaycircuit.com/#,NaN
12,XXL,nightclub/bar,"XXL, Lisboa - Portugal",https://www.lisbongaycircuit.com/#,NaN
13,DARK BY NUDE – ALBUFEIRA,nightclub/bar,"DARK BY NUDE – ALBUFEIRA, Lisboa - Portugal",https://www.lisbongaycircuit.com/#,NaN
14,THE FOREST – ALBUFEIRA,nightclub/bar,"THE FOREST – ALBUFEIRA, Lisboa - Portugal",https://www.lisbongaycircuit.com/#,NaN
15,TROMBETA BATH,sauna,"TROMBETA BATH, Lisboa - Portugal",https://www.lisbongaycircuit.com/#,NaN
16,SAUNAPOLO 56,sauna,"SAUNAPOLO 56, Lisboa - Portugal",https://www.lisbongaycircuit.com/#,NaN
17,OLISSIPO BATH,sauna,"OLISSIPO BATH, Lisboa - Portugal",https://www.lisbongaycircuit.com/#,NaN
18,3SAUNA,sauna,"3SAUNA, Lisboa - Portugal",https://www.lisbongaycircuit.com/#,NaN
19,BISTRO EDELWEISS,restaurant,"BISTRO EDELWEISS, Lisboa - Portugal",https://www.lisbongaycircuit.com/#,NaN
20,CASA DA PRAIA,restaurant,"CASA DA PRAIA, Lisboa - Portugal",https://www.lisbongaycircuit.com/#,NaN
21,DR. BERNARD,restaurant,"DR. BERNARD, Lisboa - Portugal",https://www.lisbongaycircuit.com/#,NaN
22,GLITTER’S GALLERY,restaurant,"GLITTER’S GALLERY, Lisboa - Portugal",https://www.lisbongaycircuit.com/#,NaN
23,MANNY’S PLACE,restaurant,"MANNY’S PLACE, Lisboa - Portugal",https://www.lisbongaycircuit.com/#,NaN
24,MAXIME RESTAURANTE BAR,restaurant,"MAXIME HOTEL, Lisboa - Portugal",https://www.lisbongaycircuit.com/#,NaN
25,QUERMESSE,restaurant,"QUERMESSE, Lisboa - Portugal",https://www.lisbongaycircuit.com/#,NaN
26,TANTURA MEDITERRANEAN CUISINE,restaurant,"TANTURA, Lisboa - Portugal",https://www.lisbongaycircuit.com/#,NaN
27,THE LINGERIE,restaurant,"THE LINGERIE, Lisboa - Portugal",https://www.lisbongaycircuit.com/#,NaN
28,HOTEL DO CHIADO,accommodation,"HOTEL DO CHIADO, Lisboa - Portugal",https://www.lisbongaycircuit.com/#,NaN
29,MAMA SHELTER LISBOA,accommodation,"MAMA SHELTER LISBOA, Lisboa - Portugal",https://www.lisbongaycircuit.com/#,NaN
30,HYATT REGENCY LISBOA,accommodation,"HYATT REGENCY LISBOA, Lisboa - Portugal",https://www.lisbongaycircuit.com/#,NaN

We'll create a list of locations to store the coordinates by iterating through each row of the DataFrame.

In [43]:
locations = []
for i, row in df.iterrows():
    partial_address = row['partial_address']
    location = geocode(partial_address)
    locations.append(location)
    if location:
        print(f"-> found!: {partial_address}")
    else:
        location = None
        print(f"-> NOT found.{partial_address}")

print("\ngeocoding finished.")
print(locations)

-> found!: TRUMPS, Lisboa - Portugal
-> found!: FINALMENTE CLUBE, Lisboa - Portugal
-> found!: CONSTRUCTION, Lisboa - Portugal
-> found!: PRESTIGE, Lisboa - Portugal
-> found!: 106, Lisboa - Portugal
-> found!: BAR CRU, Lisboa - Portugal
-> NOT found.CONSTRUCTION BAR – BAIRRO ALTO, Lisboa - Portugal
-> NOT found.ENTRETANTO ROOFTOP, Lisboa - Portugal
-> found!: TR3S, Lisboa - Portugal
-> found!: SHELTER BAR, Lisboa - Portugal
-> found!: SIDE BAR, Lisboa - Portugal
-> NOT found.MINIGOLF LISBON, Lisboa - Portugal
-> found!: XXL, Lisboa - Portugal
-> NOT found.DARK BY NUDE – ALBUFEIRA, Lisboa - Portugal
-> NOT found.THE FOREST – ALBUFEIRA, Lisboa - Portugal
-> found!: TROMBETA BATH, Lisboa - Portugal
-> NOT found.SAUNAPOLO 56, Lisboa - Portugal
-> NOT found.OLISSIPO BATH, Lisboa - Portugal
-> NOT found.3SAUNA, Lisboa - Portugal
-> found!: BISTRO EDELWEISS, Lisboa - Portugal
-> found!: CASA DA PRAIA, Lisboa - Portugal
-> found!: DR. BERNARD, Lisboa - Portugal
-> NOT found.GLITTER’S GALLERY, Lisboa - Portugal
-> NOT found.MANNY’S PLACE, Lisboa - Portugal
-> found!: MAXIME HOTEL, Lisboa - Portugal
-> found!: QUERMESSE, Lisboa - Portugal
-> found!: TANTURA, Lisboa - Portugal
-> NOT found.THE LINGERIE, Lisboa - Portugal
-> found!: HOTEL DO CHIADO, Lisboa - Portugal
-> found!: MAMA SHELTER LISBOA, Lisboa - Portugal
-> found!: HYATT REGENCY LISBOA, Lisboa - Portugal

geocoding finished.
[Location(Trumps Lisbon, 104B, Rua da Imprensa Nacional, São Mamede, Santo António, Lisboa, 1250-127, Portugal, (38.7174149, -9.1519004, 0.0)), Location(Finalmente Clube, 38, Rua da Palmeira, Mercês, Misericórdia, Lisboa, 1200-313, Portugal, (38.7147899, -9.1498756, 0.0)), Location(Construção do Túnel de Drenagem Monsanto-Santa Apolónia, Sete Rios, Campolide, Lisboa, Portugal, (38.7350007, -9.1674845, 0.0)), Location(Prestige, Rua das Acácias, Jardins da Parede, Carcavelos e Parede, Cascais, Lisboa, 2775-342, Portugal, (38.6957179, -9.3652949, 0.0)), Location(106, Avenida da República, Alvalade, Lisboa, 1700-173, Portugal, (38.7477356, -9.1477589, 0.0)), Location(Bar Cru, 170, Rua de São Marçal, Mercês, Santo António, Misericórdia, Lisboa, 1200-423, Portugal, (38.7159879, -9.1503266, 0.0)), None, None, Location(TR3S Lisboa, 2, Rua Ruben A. Leitão, Mercês, Misericórdia, Lisboa, 1200-392, Portugal, (38.714329, -9.1494246, 0.0)), Location(Shelter Bar, Rua da Palmeira, Mercês, Misericórdia, Lisboa, 1200-313, Portugal, (38.7148479, -9.1505212, 0.0)), Location(Side, Travessa da Espera, Bairro Alto, Misericórdia, Lisboa, 1200-050, Portugal, (38.7114735, -9.1445326, 0.0)), None, Location(XXL by Olivier, Rua Miguel Lupi, Santos-o-Velho, Prazeres, Estrela, Lisboa, 1249-077, Portugal, (38.7120545, -9.1548665, 0.0)), None, None, Location(Trombeta Bath (men only), 1C, Rua do Trombeta, Bairro Alto, Misericórdia, Lisboa, 1200-471, Portugal, (38.7115849, -9.1451568, 0.0)), None, None, None, Location(Edelweiss, 2, Rua de São Marçal, Mercês, Santo António, Misericórdia, Lisboa, 1200-421, Portugal, (38.7131474, -9.1510302, 0.0)), Location(Casa da Praia, Avenida Marginal, Junqueiro, Carcavelos e Parede, Cascais, Lisboa, 2775-604, Portugal, (38.6807465, -9.3368764, 0.0)), Location(Dr. Bernard Boavida, 119, Rua do Poço dos Negros, São Bento, Misericórdia, Lisboa, 1200-336, Portugal, (38.7097868, -9.1516671, 0.0)), None, None, Location(Maxime Hotel, 58, Praça da Alegria, São José, Santo António, Madalena, Lisboa, 1250-004, Portugal, (38.718434, -9.1453769, 0.0)), Location(Quermesse, 85, Rua da Glória, São José, Santo António, Madalena, Lisboa, 1250-115, Portugal, (38.7170987, -9.1446908, 0.0)), Location(Tantura, 1D, Rua do Trombeta, Bairro Alto, Misericórdia, Lisboa, 1200-471, Portugal, (38.7117173, -9.1451152, 0.0)), None, Location(Hotel do Chiado, 114, Rua Nova do Almada, Chiado, Santa Maria Maior, Madalena, Lisboa, 1200-290, Portugal, (38.7107197, -9.1394885, 0.0)), Location(Mama Shelter Lisboa, Rua Alexandre Herculano, São Mamede, Santo António, Lisboa, 1250-270, Portugal, (38.7209863, -9.1524216, 0.0)), Location(Hotel Hyatt Regency, 63, Rua da Junqueira, Alcântara, Lisboa, 1300-343, Portugal, (38.698324, -9.1868891, 0.0))]

We'll add latitude, longitude, point (latitude and longitude), and the establishment's name collected by Nominatim (to check if it matches what was searched) as columns to the DataFrame.

In [44]:
df['geolocated_address'] = [loc.address if loc else None for loc in locations]
df['latitude'] = [loc.latitude if loc else None for loc in locations]
df['longitude'] = [loc.longitude if loc else None for loc in locations]
df['point'] = [tuple(loc.point) if loc else None for loc in locations]
df = df.rename(columns = {'categorie':'category'})
df

,name,category,partial_address,ref,website,geolocated_address,latitude,longitude,point
0,TRUMPS,nightclub/bar,"TRUMPS, Lisboa - Portugal",https://www.lisbongaycircuit.com/#,NaN,"Trumps Lisbon, 104B, Rua da Imprensa Nacional,...",38.717415,-9.151900,"(38.7174149, -9.1519004, 0.0)"
1,FINALMENTE CLUBE,nightclub/bar,"FINALMENTE CLUBE, Lisboa - Portugal",https://www.lisbongaycircuit.com/#,NaN,"Finalmente Clube, 38, Rua da Palmeira, Mercês,...",38.714790,-9.149876,"(38.7147899, -9.1498756, 0.0)"
2,CONSTRUCTION,nightclub/bar,"CONSTRUCTION, Lisboa - Portugal",https://www.lisbongaycircuit.com/#,NaN,Construção do Túnel de Drenagem Monsanto-Santa...,38.735001,-9.167485,"(38.7350007, -9.1674845, 0.0)"
3,PRESTIGE,nightclub/bar,"PRESTIGE, Lisboa - Portugal",https://www.lisbongaycircuit.com/#,NaN,"Prestige, Rua das Acácias, Jardins da Parede, ...",38.695718,-9.365295,"(38.6957179, -9.3652949, 0.0)"
4,106,nightclub/bar,"106, Lisboa - Portugal",https://www.lisbongaycircuit.com/#,NaN,"106, Avenida da República, Alvalade, Lisboa, 1...",38.747736,-9.147759,"(38.7477356, -9.1477589, 0.0)"
5,BAR CRU,nightclub/bar,"BAR CRU, Lisboa - Portugal",https://www.lisbongaycircuit.com/#,NaN,"Bar Cru, 170, Rua de São Marçal, Mercês, Santo...",38.715988,-9.150327,"(38.7159879, -9.1503266, 0.0)"
6,CONSTRUCTION BAR - BAIRRO ALTO,nightclub/bar,"CONSTRUCTION BAR – BAIRRO ALTO, Lisboa - Portugal",https://www.lisbongaycircuit.com/#,NaN,None,NaN,NaN,None
7,ENTRETANTO ROOFTOP,nightclub/bar,"ENTRETANTO ROOFTOP, Lisboa - Portugal",https://www.lisbongaycircuit.com/#,NaN,None,NaN,NaN,None
8,TR3S,nightclub/bar,"TR3S, Lisboa - Portugal",https://www.lisbongaycircuit.com/#,NaN,"TR3S Lisboa, 2, Rua Ruben A. Leitão, Mercês, M...",38.714329,-9.149425,"(38.714329, -9.1494246, 0.0)"
9,SHELTER BAR,nightclub/bar,"SHELTER BAR, Lisboa - Portugal",https://www.lisbongaycircuit.com/#,NaN,"Shelter Bar, Rua da Palmeira, Mercês, Misericó...",38.714848,-9.150521,"(38.7148479, -9.1505212, 0.0)"
10,SIDE BAR,nightclub/bar,"SIDE BAR, Lisboa - Portugal",https://www.lisbongaycircuit.com/#,NaN,"Side, Travessa da Espera, Bairro Alto, Miseric...",38.711473,-9.144533,"(38.7114735, -9.1445326, 0.0)"
11,MINIGOLF LISBON,nightclub/bar,"MINIGOLF LISBON, Lisboa - Portugal",https://www.lisbongaycircuit.com/#,NaN,None,NaN,NaN,None
12,XXL,nightclub/bar,"XXL, Lisboa - Portugal",https://www.lisbongaycircuit.com/#,NaN,"XXL by Olivier, Rua Miguel Lupi, Santos-o-Velh...",38.712055,-9.154867,"(38.7120545, -9.1548665, 0.0)"
13,DARK BY NUDE – ALBUFEIRA,nightclub/bar,"DARK BY NUDE – ALBUFEIRA, Lisboa - Portugal",https://www.lisbongaycircuit.com/#,NaN,None,NaN,NaN,None
14,THE FOREST – ALBUFEIRA,nightclub/bar,"THE FOREST – ALBUFEIRA, Lisboa - Portugal",https://www.lisbongaycircuit.com/#,NaN,None,NaN,NaN,None
15,TROMBETA BATH,sauna,"TROMBETA BATH, Lisboa - Portugal",https://www.lisbongaycircuit.com/#,NaN,"Trombeta Bath (men only), 1C, Rua do Trombeta,...",38.711585,-9.145157,"(38.7115849, -9.1451568, 0.0)"
16,SAUNAPOLO 56,sauna,"SAUNAPOLO 56, Lisboa - Portugal",https://www.lisbongaycircuit.com/#,NaN,None,NaN,NaN,None
17,OLISSIPO BATH,sauna,"OLISSIPO BATH, Lisboa - Portugal",https://www.lisbongaycircuit.com/#,NaN,None,NaN,NaN,None
18,3SAUNA,sauna,"3SAUNA, Lisboa - Portugal",https://www.lisbongaycircuit.com/#,NaN,None,NaN,NaN,None
19,BISTRO EDELWEISS,restaurant,"BISTRO EDELWEISS, Lisboa - Portugal",https://www.lisbongaycircuit.com/#,NaN,"Edelweiss, 2, Rua de São Marçal, Mercês, Santo...",38.713147,-9.151030,"(38.7131474, -9.1510302, 0.0)"
20,CASA DA PRAIA,restaurant,"CASA DA PRAIA, Lisboa - Portugal",https://www.lisbongaycircuit.com/#,NaN,"Casa da Praia, Avenida Marginal, Junqueiro, Ca...",38.680746,-9.336876,"(38.6807465, -9.3368764, 0.0)"
21,DR. BERNARD,restaurant,"DR. BERNARD, Lisboa - Portugal",https://www.lisbongaycircuit.com/#,NaN,"Dr. Bernard Boavida, 119, Rua do Poço dos Negr...",38.709787,-9.151667,"(38.7097868, -9.1516671, 0.0)"
22,GLITTER’S GALLERY,restaurant,"GLITTER’S GALLERY, Lisboa - Portugal",https://www.lisbongaycircuit.com/#,NaN,None,NaN,NaN,None
23,MANNY’S PLACE,restaurant,"MANNY’S PLACE, Lisboa - Portugal",https://www.lisbongaycircuit.com/#,NaN,None,NaN,NaN,None
24,MAXIME RESTAURANTE BAR,restaurant,"MAXIME HOTEL, Lisboa - Portugal",https://www.lisbongaycircuit.com/#,NaN,"Maxime Hotel, 58, Praça da Alegria, São José, ...",38.718434,-9.145377,"(38.718434, -9.1453769, 0.0)"
25,QUERMESSE,restaurant,"QUERMESSE, Lisboa - Portugal",https://www.lisbongaycircuit.com/#,NaN,"Quermesse, 85, Rua da Glória, São José, Santo ...",38.717099,-9.144691,"(38.7170987, -9.1446908, 0.0)"
26,TANTURA MEDITERRANEAN CUISINE,restaurant,"TANTURA, Lisboa - Portugal",https://www.lisbongaycircuit.com/#,NaN,"Tantura, 1D, Rua do Trombeta, Bairro Alto, Mis...",38.711717,-9.145115,"(38.7117173, -9.1451152, 0.0)"
27,THE LINGERIE,restaurant,"THE LINGERIE, Lisboa - Portugal",https://www.lisbongaycircuit.com/#,NaN,None,NaN,NaN,None
28,HOTEL DO CHIADO,accommodation,"HOTEL DO CHIADO, Lisboa - Portugal",https://www.lisbongaycircuit.com/#,NaN,"Hotel do Chiado, 114, Rua Nova do Almada, Chia...",38.710720,-9.139489,"(38.7107197, -9.1394885, 0.0)"
29,MAMA SHELTER LISBOA,accommodation,"MAMA SHELTER LISBOA, Lisboa - Portugal",https://www.lisbongaycircuit.com/#,NaN,"Mama Shelter Lisboa, Rua Alexandre Herculano, ...",38.720986,-9.152422,"(38.7209863, -9.1524216, 0.0)"
30,HYATT REGENCY LISBOA,accommodation,"HYATT REGENCY LISBOA, Lisboa - Portugal",https://www.lisbongaycircuit.com/#,NaN,"Hotel Hyatt Regency, 63, Rua da Junqueira, Alc...",38.698324,-9.186889,"(38.698324, -9.1868891, 0.0)"

In [45]:
df.to_csv('geolocated_places_uncomplete.csv', index=False, encoding='utf-8-sig')

## Manually completing missing addresses
With the .csv table ready, we'll manually add the few missing addresses

In [46]:
# table edited to add missing addresses 
df_completed = pd.read_csv('geolocated_places_uncomplete_edited.csv')
df_completed

,name,category,partial_address,ref,website,geolocated_address,latitude,longitude,point
0,TRUMPS,nightclub/bar,"TRUMPS, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"Trumps Lisbon, 104B, Rua da Imprensa Nacional,...",38.717415,-9.151900,"(38.7174149, -9.1519004, 0.0)"
1,FINALMENTE CLUBE,nightclub/bar,"FINALMENTE CLUBE, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"Finalmente Clube, 38, Rua da Palmeira, Mercês,...",38.714790,-9.149876,"(38.7147899, -9.1498756, 0.0)"
2,CONSTRUCTION,nightclub/bar,"Rua da Rosa 157, Lisboa, Portugal",https://www.lisbongaycircuit.com/#\t,NaN,NaN,NaN,NaN,NaN
3,PRESTIGE,nightclub/bar,"PRESTIGE, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"Prestige, Rua das Acácias, Jardins da Parede, ...",38.695718,-9.365295,"(38.6957179, -9.3652949, 0.0)"
4,106,nightclub/bar,"106, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"106, Avenida da República, Alvalade, Lisboa, 1...",38.747736,-9.147759,"(38.7477356, -9.1477589, 0.0)"
5,BAR CRU,nightclub/bar,"BAR CRU, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"Bar Cru, 170, Rua de São Marçal, Mercês, Santo...",38.715988,-9.150327,"(38.7159879, -9.1503266, 0.0)"
6,CONSTRUCTION BAR - BAIRRO ALTO,nightclub/bar,"CONSTRUCTION BAR – BAIRRO ALTO, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,NaN,NaN,NaN,NaN
7,ENTRETANTO ROOFTOP,nightclub/bar,"Rua Nova do Almada 114, Lisboa, Portugal",https://www.lisbongaycircuit.com/#\t,NaN,NaN,NaN,NaN,NaN
8,TR3S,nightclub/bar,"TR3S, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"TR3S Lisboa, 2, Rua Ruben A. Leitão, Mercês, M...",38.714329,-9.149425,"(38.714329, -9.1494246, 0.0)"
9,SHELTER BAR,nightclub/bar,"SHELTER BAR, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"Shelter Bar, Rua da Palmeira, Mercês, Misericó...",38.714848,-9.150521,"(38.7148479, -9.1505212, 0.0)"
10,SIDE BAR,nightclub/bar,"SIDE BAR, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"Side, Travessa da Espera, Bairro Alto, Miseric...",38.711473,-9.144533,"(38.7114735, -9.1445326, 0.0)"
11,XXL,nightclub/bar,"XXL, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"XXL by Olivier, Rua Miguel Lupi, Santos-o-Velh...",38.712055,-9.154867,"(38.7120545, -9.1548665, 0.0)"
12,DARK BY NUDE – ALBUFEIRA,nightclub/bar,"DARK BY NUDE – ALBUFEIRA, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,NaN,NaN,NaN,NaN
13,THE FOREST – ALBUFEIRA,nightclub/bar,"THE FOREST – ALBUFEIRA, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,NaN,NaN,NaN,NaN
14,TROMBETA BATH,sauna,"TROMBETA BATH, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"Trombeta Bath (men only), 1C, Rua do Trombeta,...",38.711585,-9.145157,"(38.7115849, -9.1451568, 0.0)"
15,SAUNAPOLO 56,sauna,"Rua Luciano Cordeiro 56, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,NaN,NaN,NaN,NaN
16,OLISSIPO BATH,sauna,"Rua do Telhal 5, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,NaN,NaN,NaN,NaN
17,BISTRO EDELWEISS,restaurant,"BISTRO EDELWEISS, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"Edelweiss, 2, Rua de São Marçal, Mercês, Santo...",38.713147,-9.151030,"(38.7131474, -9.1510302, 0.0)"
18,CASA DA PRAIA,restaurant,"CASA DA PRAIA, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"Casa da Praia, Avenida Marginal, Junqueiro, Ca...",38.680746,-9.336876,"(38.6807465, -9.3368764, 0.0)"
19,DR. BERNARD,restaurant,"DR. BERNARD, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"Dr. Bernard Boavida, 119, Rua do Poço dos Negr...",38.709787,-9.151667,"(38.7097868, -9.1516671, 0.0)"
20,GLITTER’S GALLERY,restaurant,"Avenida Duque de Loulé 51B, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,NaN,NaN,NaN,NaN
21,MANNY’S PLACE,restaurant,"Rua da Barroca, 92. BAIRRO ALTO, Lisboa - Port...",https://www.lisbongaycircuit.com/#\t,NaN,NaN,NaN,NaN,NaN
22,MAXIME RESTAURANTE BAR,restaurant,"MAXIME HOTEL, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"Maxime Hotel, 58, Praça da Alegria, São José, ...",38.718434,-9.145377,"(38.718434, -9.1453769, 0.0)"
23,QUERMESSE,restaurant,"QUERMESSE, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"Quermesse, 85, Rua da Glória, São José, Santo ...",38.717099,-9.144691,"(38.7170987, -9.1446908, 0.0)"
24,TANTURA MEDITERRANEAN CUISINE,restaurant,"TANTURA, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"Tantura, 1D, Rua do Trombeta, Bairro Alto, Mis...",38.711717,-9.145115,"(38.7117173, -9.1451152, 0.0)"
25,THE LINGERIE,restaurant,"THE LINGERIE, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"Avenida António Augusto de Aguiar 88A, Lisboa ...",NaN,NaN,NaN
26,HOTEL DO CHIADO,accommodation,"HOTEL DO CHIADO, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"Hotel do Chiado, 114, Rua Nova do Almada, Chia...",38.710720,-9.139489,"(38.7107197, -9.1394885, 0.0)"
27,MAMA SHELTER LISBOA,accommodation,"MAMA SHELTER LISBOA, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"Mama Shelter Lisboa, Rua Alexandre Herculano, ...",38.720986,-9.152422,"(38.7209863, -9.1524216, 0.0)"
28,HYATT REGENCY LISBOA,accommodation,"HYATT REGENCY LISBOA, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"Hotel Hyatt Regency, 63, Rua da Junqueira, Alc...",38.698324,-9.186889,"(38.698324, -9.1868891, 0.0)"

In [47]:
locations = []
for i, row in df_completed.iterrows():
    partial_address = row['partial_address']
    location = geocode(partial_address)
    locations.append(location)
    if location:
        print(f"-> found!: {partial_address}")
    else:
        location = None
        print(f"-> NOT found.{partial_address}")

print("\ngeocoding finished.")

-> found!: TRUMPS, Lisboa - Portugal
-> found!: FINALMENTE CLUBE, Lisboa - Portugal
-> found!: Rua da Rosa 157, Lisboa, Portugal
-> found!: PRESTIGE, Lisboa - Portugal
-> found!: 106, Lisboa - Portugal
-> found!: BAR CRU, Lisboa - Portugal
-> NOT found.CONSTRUCTION BAR – BAIRRO ALTO, Lisboa - Portugal
-> found!: Rua Nova do Almada 114, Lisboa, Portugal
-> found!: TR3S, Lisboa - Portugal
-> found!: SHELTER BAR, Lisboa - Portugal
-> found!: SIDE BAR, Lisboa - Portugal
-> found!: XXL, Lisboa - Portugal
-> NOT found.DARK BY NUDE – ALBUFEIRA, Lisboa - Portugal
-> NOT found.THE FOREST – ALBUFEIRA, Lisboa - Portugal
-> found!: TROMBETA BATH, Lisboa - Portugal
-> found!:  Rua Luciano Cordeiro 56, Lisboa - Portugal
-> found!: Rua do Telhal 5, Lisboa - Portugal
-> found!: BISTRO EDELWEISS, Lisboa - Portugal
-> found!: CASA DA PRAIA, Lisboa - Portugal
-> found!: DR. BERNARD, Lisboa - Portugal
-> found!: Avenida Duque de Loulé 51B, Lisboa - Portugal
-> found!: Rua da Barroca, 92. BAIRRO ALTO, Lisboa - Portugal
-> found!: MAXIME HOTEL, Lisboa - Portugal
-> found!: QUERMESSE, Lisboa - Portugal
-> found!: TANTURA, Lisboa - Portugal
-> NOT found.THE LINGERIE, Lisboa - Portugal
-> found!: HOTEL DO CHIADO, Lisboa - Portugal
-> found!: MAMA SHELTER LISBOA, Lisboa - Portugal
-> found!: HYATT REGENCY LISBOA, Lisboa - Portugal

geocoding finished.

In [48]:
df_completed['geolocated_address'] = [loc.address if loc else None for loc in locations]
df_completed['latitude'] = [loc.latitude if loc else None for loc in locations]
df_completed['longitude'] = [loc.longitude if loc else None for loc in locations]
df_completed['point'] = [tuple(loc.point) if loc else None for loc in locations]
df_completed = df_completed.rename(columns = {'categorie':'category'})
df_completed

,name,category,partial_address,ref,website,geolocated_address,latitude,longitude,point
0,TRUMPS,nightclub/bar,"TRUMPS, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"Trumps Lisbon, 104B, Rua da Imprensa Nacional,...",38.717415,-9.151900,"(38.7174149, -9.1519004, 0.0)"
1,FINALMENTE CLUBE,nightclub/bar,"FINALMENTE CLUBE, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"Finalmente Clube, 38, Rua da Palmeira, Mercês,...",38.714790,-9.149876,"(38.7147899, -9.1498756, 0.0)"
2,CONSTRUCTION,nightclub/bar,"Rua da Rosa 157, Lisboa, Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"Rua da Rosa, Bairro Alto, Misericórdia, Lisboa...",38.713402,-9.145462,"(38.7134023, -9.1454618, 0.0)"
3,PRESTIGE,nightclub/bar,"PRESTIGE, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"Prestige, Rua das Acácias, Jardins da Parede, ...",38.695718,-9.365295,"(38.6957179, -9.3652949, 0.0)"
4,106,nightclub/bar,"106, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"106, Avenida da República, Alvalade, Lisboa, 1...",38.747736,-9.147759,"(38.7477356, -9.1477589, 0.0)"
5,BAR CRU,nightclub/bar,"BAR CRU, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"Bar Cru, 170, Rua de São Marçal, Mercês, Santo...",38.715988,-9.150327,"(38.7159879, -9.1503266, 0.0)"
6,CONSTRUCTION BAR - BAIRRO ALTO,nightclub/bar,"CONSTRUCTION BAR – BAIRRO ALTO, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,None,NaN,NaN,None
7,ENTRETANTO ROOFTOP,nightclub/bar,"Rua Nova do Almada 114, Lisboa, Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"Hotel do Chiado, 114, Rua Nova do Almada, Chia...",38.710720,-9.139489,"(38.7107197, -9.1394885, 0.0)"
8,TR3S,nightclub/bar,"TR3S, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"TR3S Lisboa, 2, Rua Ruben A. Leitão, Mercês, M...",38.714329,-9.149425,"(38.714329, -9.1494246, 0.0)"
9,SHELTER BAR,nightclub/bar,"SHELTER BAR, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"Shelter Bar, Rua da Palmeira, Mercês, Misericó...",38.714848,-9.150521,"(38.7148479, -9.1505212, 0.0)"
10,SIDE BAR,nightclub/bar,"SIDE BAR, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"Side, Travessa da Espera, Bairro Alto, Miseric...",38.711473,-9.144533,"(38.7114735, -9.1445326, 0.0)"
11,XXL,nightclub/bar,"XXL, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"XXL by Olivier, Rua Miguel Lupi, Santos-o-Velh...",38.712055,-9.154867,"(38.7120545, -9.1548665, 0.0)"
12,DARK BY NUDE – ALBUFEIRA,nightclub/bar,"DARK BY NUDE – ALBUFEIRA, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,None,NaN,NaN,None
13,THE FOREST – ALBUFEIRA,nightclub/bar,"THE FOREST – ALBUFEIRA, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,None,NaN,NaN,None
14,TROMBETA BATH,sauna,"TROMBETA BATH, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"Trombeta Bath (men only), 1C, Rua do Trombeta,...",38.711585,-9.145157,"(38.7115849, -9.1451568, 0.0)"
15,SAUNAPOLO 56,sauna,"Rua Luciano Cordeiro 56, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"Rua Luciano Cordeiro, Bairro Camões, Santo Ant...",38.725931,-9.144917,"(38.7259314, -9.144917, 0.0)"
16,OLISSIPO BATH,sauna,"Rua do Telhal 5, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"5, Rua do Telhal, São José, Santo António, Mad...",38.719195,-9.142850,"(38.7191952, -9.1428501, 0.0)"
17,BISTRO EDELWEISS,restaurant,"BISTRO EDELWEISS, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"Edelweiss, 2, Rua de São Marçal, Mercês, Santo...",38.713147,-9.151030,"(38.7131474, -9.1510302, 0.0)"
18,CASA DA PRAIA,restaurant,"CASA DA PRAIA, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"Casa da Praia, Avenida Marginal, Junqueiro, Ca...",38.680746,-9.336876,"(38.6807465, -9.3368764, 0.0)"
19,DR. BERNARD,restaurant,"DR. BERNARD, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"Dr. Bernard Boavida, 119, Rua do Poço dos Negr...",38.709787,-9.151667,"(38.7097868, -9.1516671, 0.0)"
20,GLITTER’S GALLERY,restaurant,"Avenida Duque de Loulé 51B, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"Avenida Duque de Loulé, Coração de Jesus, Sant...",38.725261,-9.148934,"(38.7252609, -9.1489343, 0.0)"
21,MANNY’S PLACE,restaurant,"Rua da Barroca, 92. BAIRRO ALTO, Lisboa - Port...",https://www.lisbongaycircuit.com/#\t,NaN,"Rua da Barroca, Bairro Alto, Misericórdia, Lis...",38.711891,-9.144530,"(38.711891, -9.1445299, 0.0)"
22,MAXIME RESTAURANTE BAR,restaurant,"MAXIME HOTEL, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"Maxime Hotel, 58, Praça da Alegria, São José, ...",38.718434,-9.145377,"(38.718434, -9.1453769, 0.0)"
23,QUERMESSE,restaurant,"QUERMESSE, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"Quermesse, 85, Rua da Glória, São José, Santo ...",38.717099,-9.144691,"(38.7170987, -9.1446908, 0.0)"
24,TANTURA MEDITERRANEAN CUISINE,restaurant,"TANTURA, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"Tantura, 1D, Rua do Trombeta, Bairro Alto, Mis...",38.711717,-9.145115,"(38.7117173, -9.1451152, 0.0)"
25,THE LINGERIE,restaurant,"THE LINGERIE, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,None,NaN,NaN,None
26,HOTEL DO CHIADO,accommodation,"HOTEL DO CHIADO, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"Hotel do Chiado, 114, Rua Nova do Almada, Chia...",38.710720,-9.139489,"(38.7107197, -9.1394885, 0.0)"
27,MAMA SHELTER LISBOA,accommodation,"MAMA SHELTER LISBOA, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"Mama Shelter Lisboa, Rua Alexandre Herculano, ...",38.720986,-9.152422,"(38.7209863, -9.1524216, 0.0)"
28,HYATT REGENCY LISBOA,accommodation,"HYATT REGENCY LISBOA, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"Hotel Hyatt Regency, 63, Rua da Junqueira, Alc...",38.698324,-9.186889,"(38.698324, -9.1868891, 0.0)"

In [49]:
df_completed.to_csv('geolocated_places_complete.csv', index=False, encoding='utf-8-sig' )

# Plotando bares em um mapa usando Folium

In [50]:
import folium

categories_colors = {
    'nightclub/bar': 'pink',       
    'sauna': 'red',              
    'restaurant': 'orange',        
    'association': 'purple',      
    'accommodation': 'green',    
    'beach': 'ciano',        
    }

default_color = 'gray'
center = [38.7223, -9.1393]
lisbon_map = folium.Map(location=center, zoom_start=14)

for i, row in df.iterrows():
    if pd.notna(row['latitude']) and pd.notna(row['longitude']):
        coordinates = [row['latitude'], row['longitude']]
        name = row['name']
        address = row['geolocated_address']
        category = row['category']
        marker_color = categories_colors.get(category, default_color)
        html_popup = f"""
        <h4>{name}</h4>
        <p>
        <b>Address: </b> {address}<br>
        </p>
        <p>
        <b>Category: </b> {category}<br>
        </p>
        """
        popup = folium.Popup(html_popup, max_width=250)
        folium.Marker(location=coordinates, popup=popup, tooltip=name, icon=folium.Icon(color=marker_color, icon='info-sign') ).add_to(lisbon_map)

lisbon_map.save('lisbon_places_map.html')
lisbon_map