# Complete map with all data collect
We'll start mixing the to .csv's, trasnforming in to a DataFrame and use the .concat() function

In [169]:
import pandas as pd
import folium
from folium.plugins import Geocoder # para barra de pesquisa
from branca.element import Element # para legenda

In [82]:
df1 = pd.read_csv('geolocated_bars.csv')
df2 = pd.read_csv('geolocated_places_complete.csv')

sub1 = pd.DataFrame()
sub2 = pd.DataFrame()

In [83]:
df1

,name,address,category,website,ref,geolocated_address,latitude,longitude,point
0,Trumps,"Rua da Imprensa Nacional, 104 B, Lisboa - Port...",nightclub/bar,NaN,https://www.timeout.pt/lisboa/pt/noite/os-melh...,"Trumps Lisbon, 104B, Rua da Imprensa Nacional,...",38.717415,-9.151900,"(38.7174149, -9.1519004, 0.0)"
1,Society,"Rua Cecílio de Sousa, 72, Lisboa - Portugal",nightclub/bar,NaN,https://www.timeout.pt/lisboa/pt/noite/os-melh...,"Rua Cecílio de Sousa, Mercês, Santo António, M...",38.716060,-9.150158,"(38.7160598, -9.1501583, 0.0)"
2,Friends,"Travessa da Água da Flor, 17, Lisboa - Portugal",nightclub/bar,NaN,https://www.timeout.pt/lisboa/pt/noite/os-melh...,"Travessa da Água-da-Flor, Bairro Alto, Miseric...",38.713582,-9.144639,"(38.7135817, -9.144639, 0.0)"
3,Posh Club,"Rua de São Bento, 157, Lisboa - Portugal",nightclub/bar,NaN,https://www.timeout.pt/lisboa/pt/noite/os-melh...,"157, Rua de São Bento, Amoreiras, Santa Isabel...",38.714759,-9.154028,"(38.7147594, -9.1540276, 0.0)"
4,Corvo,"Calçada Engenheiro Miguel Pais, 18, Lisboa - P...",nightclub/bar,NaN,https://www.timeout.pt/lisboa/pt/noite/os-melh...,"Calçada Engenheiro Miguel Pais, São Mamede, Sa...",38.717143,-9.151472,"(38.7171429, -9.1514721, 0.0)"
5,Bar Cru,"Rua de São Marçal, 170, Lisboa - Portugal",nightclub/bar,NaN,https://www.timeout.pt/lisboa/pt/noite/os-melh...,"Bar Cru, 170, Rua de São Marçal, Mercês, Santo...",38.715988,-9.150327,"(38.7159879, -9.1503266, 0.0)"
6,Maria Lisboa,"Rua da Atalaia, 97, Lisboa - Portugal",nightclub/bar,NaN,https://www.timeout.pt/lisboa/pt/noite/os-melh...,"Rua da Atalaia, Bairro Alto, Misericórdia, Lis...",38.712770,-9.145032,"(38.71277, -9.1450324, 0.0)"
7,Vlada Lounge,"Rua Rosa Damasceno 8, Lisboa - Portugal",nightclub/bar,NaN,https://www.timeout.pt/lisboa/pt/noite/os-melh...,"8, Rua Rosa Damasceno, Arroios, Lisboa, 1900-9...",38.735957,-9.131970,"(38.7359566, -9.1319704, 0.0)"
8,Pride Burlesque,"Rua da Rosa, 159, Lisboa - Portugal",nightclub/bar,NaN,https://www.timeout.pt/lisboa/pt/noite/os-melh...,"Rua da Rosa, Bairro Alto, Misericórdia, Lisboa...",38.710932,-9.145583,"(38.7109322, -9.1455829, 0.0)"
9,Construction,"Rua do Instituto Industrial, 6, Lisboa - Portugal",nightclub/bar,NaN,https://www.timeout.pt/lisboa/pt/noite/os-melh...,"Rua do Instituto Industrial, São Bento, Miseri...",38.708284,-9.150524,"(38.7082836, -9.1505239, 0.0)"
10,Finalmente,"Rua da Palmeira, 38, Lisboa - Portugal",nightclub/bar,NaN,https://www.timeout.pt/lisboa/pt/noite/os-melh...,"Finalmente Clube, 38, Rua da Palmeira, Mercês,...",38.714790,-9.149876,"(38.7147899, -9.1498756, 0.0)"
11,Drako Club,"Rua Nogueira e Sousa, 11, Lisboa - Portugal",nightclub/bar,NaN,https://www.timeout.pt/lisboa/pt/noite/os-melh...,"11, Rua Nogueira e Sousa, Bairro Camões, Santo...",38.723453,-9.143187,"(38.7234529, -9.1431873, 0.0)"
12,Purex,"Rua das Salgadeiras, 28, Lisboa - Portugal",nightclub/bar,NaN,https://www.timeout.pt/lisboa/pt/noite/os-melh...,"28, Rua das Salgadeiras, Bairro Alto, Misericó...",38.710970,-9.144427,"(38.7109696, -9.1444266, 0.0)"
13,TR3S,"Rua Ruben A. Leitão, 2 A, Lisboa - Portugal",nightclub/bar,NaN,https://www.timeout.pt/lisboa/pt/noite/os-melh...,"TR3S Lisboa, 2, Rua Ruben A. Leitão, Mercês, M...",38.714329,-9.149425,"(38.714329, -9.1494246, 0.0)"
14,WoofLX (FECHADO),"Rua da Palmeira, 44 B, Lisboa - Portugal",nightclub/bar,NaN,https://www.timeout.pt/lisboa/pt/noite/os-melh...,"Rua da Palmeira, Mercês, Misericórdia, Lisboa,...",38.714887,-9.149177,"(38.7148874, -9.149177, 0.0)"
15,WoofX,"Rua Manuel Bernardes, 2B, Lisboa - Portugal",nightclub/bar,NaN,https://www.timeout.pt/lisboa/pt/noite/os-melh...,"woof x Lisbon, 2 B, Rua Manuel Bernardes, Merc...",38.714739,-9.152072,"(38.7147389, -9.1520719, 0.0)"
16,Bar 106,"Rua de São Marçal, 106/108, Lisboa - Portugal",nightclub/bar,NaN,https://www.timeout.pt/lisboa/pt/noite/os-melh...,"Rua de São Marçal, Mercês, Santo António, Mise...",38.715234,-9.150818,"(38.7152343, -9.150818, 0.0)"
17,Shelter,"Rua da Palmeira, 43 A, Lisboa - Portugal",nightclub/bar,NaN,https://www.timeout.pt/lisboa/pt/noite/os-melh...,"43, Rua da Palmeira, Mercês, Misericórdia, Lis...",38.714861,-9.150507,"(38.7148612, -9.1505072, 0.0)"

In [84]:
df2

,name,category,partial_address,ref,website,geolocated_address,latitude,longitude,point
0,TRUMPS,nightclub/bar,"TRUMPS, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"Trumps Lisbon, 104B, Rua da Imprensa Nacional,...",38.717415,-9.151900,"(38.7174149, -9.1519004, 0.0)"
1,FINALMENTE CLUBE,nightclub/bar,"FINALMENTE CLUBE, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"Finalmente Clube, 38, Rua da Palmeira, Mercês,...",38.714790,-9.149876,"(38.7147899, -9.1498756, 0.0)"
2,CONSTRUCTION,nightclub/bar,"Rua da Rosa 157, Lisboa, Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"Rua da Rosa, Bairro Alto, Misericórdia, Lisboa...",38.713402,-9.145462,"(38.7134023, -9.1454618, 0.0)"
3,PRESTIGE,nightclub/bar,"PRESTIGE, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"Prestige, Rua das Acácias, Jardins da Parede, ...",38.695718,-9.365295,"(38.6957179, -9.3652949, 0.0)"
4,106,nightclub/bar,"106, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"106, Avenida da República, Alvalade, Lisboa, 1...",38.747736,-9.147759,"(38.7477356, -9.1477589, 0.0)"
5,BAR CRU,nightclub/bar,"BAR CRU, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"Bar Cru, 170, Rua de São Marçal, Mercês, Santo...",38.715988,-9.150327,"(38.7159879, -9.1503266, 0.0)"
6,CONSTRUCTION BAR - BAIRRO ALTO,nightclub/bar,"CONSTRUCTION BAR – BAIRRO ALTO, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,NaN,NaN,NaN,NaN
7,ENTRETANTO ROOFTOP,nightclub/bar,"Rua Nova do Almada 114, Lisboa, Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"Hotel do Chiado, 114, Rua Nova do Almada, Chia...",38.710720,-9.139489,"(38.7107197, -9.1394885, 0.0)"
8,TR3S,nightclub/bar,"TR3S, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"TR3S Lisboa, 2, Rua Ruben A. Leitão, Mercês, M...",38.714329,-9.149425,"(38.714329, -9.1494246, 0.0)"
9,SHELTER BAR,nightclub/bar,"SHELTER BAR, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"Shelter Bar, Rua da Palmeira, Mercês, Misericó...",38.714848,-9.150521,"(38.7148479, -9.1505212, 0.0)"
10,SIDE BAR,nightclub/bar,"SIDE BAR, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"Side, Travessa da Espera, Bairro Alto, Miseric...",38.711473,-9.144533,"(38.7114735, -9.1445326, 0.0)"
11,XXL,nightclub/bar,"XXL, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"XXL by Olivier, Rua Miguel Lupi, Santos-o-Velh...",38.712055,-9.154867,"(38.7120545, -9.1548665, 0.0)"
12,DARK BY NUDE – ALBUFEIRA,nightclub/bar,"DARK BY NUDE – ALBUFEIRA, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,NaN,NaN,NaN,NaN
13,THE FOREST – ALBUFEIRA,nightclub/bar,"THE FOREST – ALBUFEIRA, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,NaN,NaN,NaN,NaN
14,TROMBETA BATH,sauna,"TROMBETA BATH, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"Trombeta Bath (men only), 1C, Rua do Trombeta,...",38.711585,-9.145157,"(38.7115849, -9.1451568, 0.0)"
15,SAUNAPOLO 56,sauna,"Rua Luciano Cordeiro 56, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"Rua Luciano Cordeiro, Bairro Camões, Santo Ant...",38.725931,-9.144917,"(38.7259314, -9.144917, 0.0)"
16,OLISSIPO BATH,sauna,"Rua do Telhal 5, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"5, Rua do Telhal, São José, Santo António, Mad...",38.719195,-9.142850,"(38.7191952, -9.1428501, 0.0)"
17,BISTRO EDELWEISS,restaurant,"BISTRO EDELWEISS, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"Edelweiss, 2, Rua de São Marçal, Mercês, Santo...",38.713147,-9.151030,"(38.7131474, -9.1510302, 0.0)"
18,CASA DA PRAIA,restaurant,"CASA DA PRAIA, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"Casa da Praia, Avenida Marginal, Junqueiro, Ca...",38.680746,-9.336876,"(38.6807465, -9.3368764, 0.0)"
19,DR. BERNARD,restaurant,"DR. BERNARD, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"Dr. Bernard Boavida, 119, Rua do Poço dos Negr...",38.709787,-9.151667,"(38.7097868, -9.1516671, 0.0)"
20,GLITTER’S GALLERY,restaurant,"Avenida Duque de Loulé 51B, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"Avenida Duque de Loulé, Coração de Jesus, Sant...",38.725261,-9.148934,"(38.7252609, -9.1489343, 0.0)"
21,MANNY’S PLACE,restaurant,"Rua da Barroca, 92. BAIRRO ALTO, Lisboa - Port...",https://www.lisbongaycircuit.com/#\t,NaN,"Rua da Barroca, Bairro Alto, Misericórdia, Lis...",38.711891,-9.144530,"(38.711891, -9.1445299, 0.0)"
22,MAXIME RESTAURANTE BAR,restaurant,"MAXIME HOTEL, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"Maxime Hotel, 58, Praça da Alegria, São José, ...",38.718434,-9.145377,"(38.718434, -9.1453769, 0.0)"
23,QUERMESSE,restaurant,"QUERMESSE, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"Quermesse, 85, Rua da Glória, São José, Santo ...",38.717099,-9.144691,"(38.7170987, -9.1446908, 0.0)"
24,TANTURA MEDITERRANEAN CUISINE,restaurant,"TANTURA, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"Tantura, 1D, Rua do Trombeta, Bairro Alto, Mis...",38.711717,-9.145115,"(38.7117173, -9.1451152, 0.0)"
25,THE LINGERIE,restaurant,"THE LINGERIE, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,NaN,NaN,NaN,NaN
26,HOTEL DO CHIADO,accommodation,"HOTEL DO CHIADO, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"Hotel do Chiado, 114, Rua Nova do Almada, Chia...",38.710720,-9.139489,"(38.7107197, -9.1394885, 0.0)"
27,MAMA SHELTER LISBOA,accommodation,"MAMA SHELTER LISBOA, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"Mama Shelter Lisboa, Rua Alexandre Herculano, ...",38.720986,-9.152422,"(38.7209863, -9.1524216, 0.0)"
28,HYATT REGENCY LISBOA,accommodation,"HYATT REGENCY LISBOA, Lisboa - Portugal",https://www.lisbongaycircuit.com/#\t,NaN,"Hotel Hyatt Regency, 63, Rua da Junqueira, Alc...",38.698324,-9.186889,"(38.698324, -9.1868891, 0.0)"

In [85]:
subcolumns = ['name', 'category', 'geolocated_address', 'ref', 'website', 'latitude', 'longitude']
sub1 = df1[subcolumns]
sub2 = df2[subcolumns]

df = pd.concat([sub1, sub2])
df

,name,category,geolocated_address,ref,website,latitude,longitude
0,Trumps,nightclub/bar,"Trumps Lisbon, 104B, Rua da Imprensa Nacional,...",https://www.timeout.pt/lisboa/pt/noite/os-melh...,NaN,38.717415,-9.151900
1,Society,nightclub/bar,"Rua Cecílio de Sousa, Mercês, Santo António, M...",https://www.timeout.pt/lisboa/pt/noite/os-melh...,NaN,38.716060,-9.150158
2,Friends,nightclub/bar,"Travessa da Água-da-Flor, Bairro Alto, Miseric...",https://www.timeout.pt/lisboa/pt/noite/os-melh...,NaN,38.713582,-9.144639
3,Posh Club,nightclub/bar,"157, Rua de São Bento, Amoreiras, Santa Isabel...",https://www.timeout.pt/lisboa/pt/noite/os-melh...,NaN,38.714759,-9.154028
4,Corvo,nightclub/bar,"Calçada Engenheiro Miguel Pais, São Mamede, Sa...",https://www.timeout.pt/lisboa/pt/noite/os-melh...,NaN,38.717143,-9.151472
5,Bar Cru,nightclub/bar,"Bar Cru, 170, Rua de São Marçal, Mercês, Santo...",https://www.timeout.pt/lisboa/pt/noite/os-melh...,NaN,38.715988,-9.150327
6,Maria Lisboa,nightclub/bar,"Rua da Atalaia, Bairro Alto, Misericórdia, Lis...",https://www.timeout.pt/lisboa/pt/noite/os-melh...,NaN,38.712770,-9.145032
7,Vlada Lounge,nightclub/bar,"8, Rua Rosa Damasceno, Arroios, Lisboa, 1900-9...",https://www.timeout.pt/lisboa/pt/noite/os-melh...,NaN,38.735957,-9.131970
8,Pride Burlesque,nightclub/bar,"Rua da Rosa, Bairro Alto, Misericórdia, Lisboa...",https://www.timeout.pt/lisboa/pt/noite/os-melh...,NaN,38.710932,-9.145583
9,Construction,nightclub/bar,"Rua do Instituto Industrial, São Bento, Miseri...",https://www.timeout.pt/lisboa/pt/noite/os-melh...,NaN,38.708284,-9.150524
10,Finalmente,nightclub/bar,"Finalmente Clube, 38, Rua da Palmeira, Mercês,...",https://www.timeout.pt/lisboa/pt/noite/os-melh...,NaN,38.714790,-9.149876
11,Drako Club,nightclub/bar,"11, Rua Nogueira e Sousa, Bairro Camões, Santo...",https://www.timeout.pt/lisboa/pt/noite/os-melh...,NaN,38.723453,-9.143187
12,Purex,nightclub/bar,"28, Rua das Salgadeiras, Bairro Alto, Misericó...",https://www.timeout.pt/lisboa/pt/noite/os-melh...,NaN,38.710970,-9.144427
13,TR3S,nightclub/bar,"TR3S Lisboa, 2, Rua Ruben A. Leitão, Mercês, M...",https://www.timeout.pt/lisboa/pt/noite/os-melh...,NaN,38.714329,-9.149425
14,WoofLX (FECHADO),nightclub/bar,"Rua da Palmeira, Mercês, Misericórdia, Lisboa,...",https://www.timeout.pt/lisboa/pt/noite/os-melh...,NaN,38.714887,-9.149177
15,WoofX,nightclub/bar,"woof x Lisbon, 2 B, Rua Manuel Bernardes, Merc...",https://www.timeout.pt/lisboa/pt/noite/os-melh...,NaN,38.714739,-9.152072
16,Bar 106,nightclub/bar,"Rua de São Marçal, Mercês, Santo António, Mise...",https://www.timeout.pt/lisboa/pt/noite/os-melh...,NaN,38.715234,-9.150818
17,Shelter,nightclub/bar,"43, Rua da Palmeira, Mercês, Misericórdia, Lis...",https://www.timeout.pt/lisboa/pt/noite/os-melh...,NaN,38.714861,-9.150507
0,TRUMPS,nightclub/bar,"Trumps Lisbon, 104B, Rua da Imprensa Nacional,...",https://www.lisbongaycircuit.com/#\t,NaN,38.717415,-9.151900
1,FINALMENTE CLUBE,nightclub/bar,"Finalmente Clube, 38, Rua da Palmeira, Mercês,...",https://www.lisbongaycircuit.com/#\t,NaN,38.714790,-9.149876
2,CONSTRUCTION,nightclub/bar,"Rua da Rosa, Bairro Alto, Misericórdia, Lisboa...",https://www.lisbongaycircuit.com/#\t,NaN,38.713402,-9.145462
3,PRESTIGE,nightclub/bar,"Prestige, Rua das Acácias, Jardins da Parede, ...",https://www.lisbongaycircuit.com/#\t,NaN,38.695718,-9.365295
4,106,nightclub/bar,"106, Avenida da República, Alvalade, Lisboa, 1...",https://www.lisbongaycircuit.com/#\t,NaN,38.747736,-9.147759
5,BAR CRU,nightclub/bar,"Bar Cru, 170, Rua de São Marçal, Mercês, Santo...",https://www.lisbongaycircuit.com/#\t,NaN,38.715988,-9.150327
6,CONSTRUCTION BAR - BAIRRO ALTO,nightclub/bar,NaN,https://www.lisbongaycircuit.com/#\t,NaN,NaN,NaN
7,ENTRETANTO ROOFTOP,nightclub/bar,"Hotel do Chiado, 114, Rua Nova do Almada, Chia...",https://www.lisbongaycircuit.com/#\t,NaN,38.710720,-9.139489
8,TR3S,nightclub/bar,"TR3S Lisboa, 2, Rua Ruben A. Leitão, Mercês, M...",https://www.lisbongaycircuit.com/#\t,NaN,38.714329,-9.149425
9,SHELTER BAR,nightclub/bar,"Shelter Bar, Rua da Palmeira, Mercês, Misericó...",https://www.lisbongaycircuit.com/#\t,NaN,38.714848,-9.150521
10,SIDE BAR,nightclub/bar,"Side, Travessa da Espera, Bairro Alto, Miseric...",https://www.lisbongaycircuit.com/#\t,NaN,38.711473,-9.144533
11,XXL,nightclub/bar,"XXL by Olivier, Rua Miguel Lupi, Santos-o-Velh...",https://www.lisbongaycircuit.com/#\t,NaN,38.712055,-9.154867
12,DARK BY NUDE – ALBUFEIRA,nightclub/bar,NaN,https://www.lisbongaycircuit.com/#\t,NaN,NaN,NaN
13,THE FOREST – ALBUFEIRA,nightclub/bar,NaN,https://www.lisbongaycircuit.com/#\t,NaN,NaN,NaN
14,TROMBETA BATH,sauna,"Trombeta Bath (men only), 1C, Rua do Trombeta,...",https://www.lisbongaycircuit.com/#\t,NaN,38.711585,-9.145157
15,SAUNAPOLO 56,sauna,"Rua Luciano Cordeiro, Bairro Camões, Santo Ant...",https://www.lisbongaycircuit.com/#\t,NaN,38.725931,-9.144917
16,OLISSIPO BATH,sauna,"5, Rua do Telhal, São José, Santo António, Mad...",https://www.lisbongaycircuit.com/#\t,NaN,38.719195,-9.142850
17,BISTRO EDELWEISS,restaurant,"Edelweiss, 2, Rua de São Marçal, Mercês, Santo...",https://www.lisbongaycircuit.com/#\t,NaN,38.713147,-9.151030
18,CASA DA PRAIA,restaurant,"Casa da Praia, Avenida Marginal, Junqueiro, Ca...",https://www.lisbongaycircuit.com/#\t,NaN,38.680746,-9.336876
19,DR. BERNARD,restaurant,"Dr. Bernard Boavida, 119, Rua do Poço dos Negr...",https://www.lisbongaycircuit.com/#\t,NaN,38.709787,-9.151667
20,GLITTER’S GALLERY,restaurant,"Avenida Duque de Loulé, Coração de Jesus, Sant...",https://www.lisbongaycircuit.com/#\t,NaN,38.725261,-9.148934
21,MANNY’S PLACE,restaurant,"Rua da Barroca, Bairro Alto, Misericórdia, Lis...",https://www.lisbongaycircuit.com/#\t,NaN,38.711891,-9.144530
22,MAXIME RESTAURANTE BAR,restaurant,"Maxime Hotel, 58, Praça da Alegria, São José, ...",https://www.lisbongaycircuit.com/#\t,NaN,38.718434,-9.145377
23,QUERMESSE,restaurant,"Quermesse, 85, Rua da Glória, São José, Santo ...",https://www.lisbongaycircuit.com/#\t,NaN,38.717099,-9.144691
24,TANTURA MEDITERRANEAN CUISINE,restaurant,"Tantura, 1D, Rua do Trombeta, Bairro Alto, Mis...",https://www.lisbongaycircuit.com/#\t,NaN,38.711717,-9.145115
25,THE LINGERIE,restaurant,NaN,https://www.lisbongaycircuit.com/#\t,NaN,NaN,NaN
26,HOTEL DO CHIADO,accommodation,"Hotel do Chiado, 114, Rua Nova do Almada, Chia...",https://www.lisbongaycircuit.com/#\t,NaN,38.710720,-9.139489
27,MAMA SHELTER LISBOA,accommodation,"Mama Shelter Lisboa, Rua Alexandre Herculano, ...",https://www.lisbongaycircuit.com/#\t,NaN,38.720986,-9.152422
28,HYATT REGENCY LISBOA,accommodation,"Hotel Hyatt Regency, 63, Rua da Junqueira, Alc...",https://www.lisbongaycircuit.com/#\t,NaN,38.698324,-9.186889

In [86]:
# standardizing names
df['name'] = df['name'].str.upper()

# correcting names
df.loc[df['name'] == 'FINALMENTE', 'name'] = 'FINALMENTE CLUBE'
df.loc[df['name'] == 'CONSTRUCTION BAR - BAIRRO ALTO', 'name'] = 'CONSTRUCTION'
df.loc[df['name'] == 'SHELTER BAR', 'name'] = 'SHELTER'

#cleaning addresses
df = df.dropna(subset=['geolocated_address', 'latitude', 'longitude'])
df = df[df['name'] != 'WOOFLX (FECHADO)	'].copy()
df = df[~df['name'].isin(['WOOFLX (FECHADO)'])].copy()
df = df[df['name'] != '106'].copy()
df = df[~df['name'].isin(['106'])].copy()


#removing duplicates
df_limpo = df.drop_duplicates(subset=['name'])

# saving
df_limpo.to_csv('completed_places.csv', index=False, encoding='utf-8-sig')
df_limpo

,name,category,geolocated_address,ref,website,latitude,longitude
0,TRUMPS,nightclub/bar,"Trumps Lisbon, 104B, Rua da Imprensa Nacional,...",https://www.timeout.pt/lisboa/pt/noite/os-melh...,NaN,38.717415,-9.151900
1,SOCIETY,nightclub/bar,"Rua Cecílio de Sousa, Mercês, Santo António, M...",https://www.timeout.pt/lisboa/pt/noite/os-melh...,NaN,38.716060,-9.150158
2,FRIENDS,nightclub/bar,"Travessa da Água-da-Flor, Bairro Alto, Miseric...",https://www.timeout.pt/lisboa/pt/noite/os-melh...,NaN,38.713582,-9.144639
3,POSH CLUB,nightclub/bar,"157, Rua de São Bento, Amoreiras, Santa Isabel...",https://www.timeout.pt/lisboa/pt/noite/os-melh...,NaN,38.714759,-9.154028
4,CORVO,nightclub/bar,"Calçada Engenheiro Miguel Pais, São Mamede, Sa...",https://www.timeout.pt/lisboa/pt/noite/os-melh...,NaN,38.717143,-9.151472
5,BAR CRU,nightclub/bar,"Bar Cru, 170, Rua de São Marçal, Mercês, Santo...",https://www.timeout.pt/lisboa/pt/noite/os-melh...,NaN,38.715988,-9.150327
6,MARIA LISBOA,nightclub/bar,"Rua da Atalaia, Bairro Alto, Misericórdia, Lis...",https://www.timeout.pt/lisboa/pt/noite/os-melh...,NaN,38.712770,-9.145032
7,VLADA LOUNGE,nightclub/bar,"8, Rua Rosa Damasceno, Arroios, Lisboa, 1900-9...",https://www.timeout.pt/lisboa/pt/noite/os-melh...,NaN,38.735957,-9.131970
8,PRIDE BURLESQUE,nightclub/bar,"Rua da Rosa, Bairro Alto, Misericórdia, Lisboa...",https://www.timeout.pt/lisboa/pt/noite/os-melh...,NaN,38.710932,-9.145583
9,CONSTRUCTION,nightclub/bar,"Rua do Instituto Industrial, São Bento, Miseri...",https://www.timeout.pt/lisboa/pt/noite/os-melh...,NaN,38.708284,-9.150524
10,FINALMENTE CLUBE,nightclub/bar,"Finalmente Clube, 38, Rua da Palmeira, Mercês,...",https://www.timeout.pt/lisboa/pt/noite/os-melh...,NaN,38.714790,-9.149876
11,DRAKO CLUB,nightclub/bar,"11, Rua Nogueira e Sousa, Bairro Camões, Santo...",https://www.timeout.pt/lisboa/pt/noite/os-melh...,NaN,38.723453,-9.143187
12,PUREX,nightclub/bar,"28, Rua das Salgadeiras, Bairro Alto, Misericó...",https://www.timeout.pt/lisboa/pt/noite/os-melh...,NaN,38.710970,-9.144427
13,TR3S,nightclub/bar,"TR3S Lisboa, 2, Rua Ruben A. Leitão, Mercês, M...",https://www.timeout.pt/lisboa/pt/noite/os-melh...,NaN,38.714329,-9.149425
15,WOOFX,nightclub/bar,"woof x Lisbon, 2 B, Rua Manuel Bernardes, Merc...",https://www.timeout.pt/lisboa/pt/noite/os-melh...,NaN,38.714739,-9.152072
16,BAR 106,nightclub/bar,"Rua de São Marçal, Mercês, Santo António, Mise...",https://www.timeout.pt/lisboa/pt/noite/os-melh...,NaN,38.715234,-9.150818
17,SHELTER,nightclub/bar,"43, Rua da Palmeira, Mercês, Misericórdia, Lis...",https://www.timeout.pt/lisboa/pt/noite/os-melh...,NaN,38.714861,-9.150507
3,PRESTIGE,nightclub/bar,"Prestige, Rua das Acácias, Jardins da Parede, ...",https://www.lisbongaycircuit.com/#\t,NaN,38.695718,-9.365295
7,ENTRETANTO ROOFTOP,nightclub/bar,"Hotel do Chiado, 114, Rua Nova do Almada, Chia...",https://www.lisbongaycircuit.com/#\t,NaN,38.710720,-9.139489
10,SIDE BAR,nightclub/bar,"Side, Travessa da Espera, Bairro Alto, Miseric...",https://www.lisbongaycircuit.com/#\t,NaN,38.711473,-9.144533
11,XXL,nightclub/bar,"XXL by Olivier, Rua Miguel Lupi, Santos-o-Velh...",https://www.lisbongaycircuit.com/#\t,NaN,38.712055,-9.154867
14,TROMBETA BATH,sauna,"Trombeta Bath (men only), 1C, Rua do Trombeta,...",https://www.lisbongaycircuit.com/#\t,NaN,38.711585,-9.145157
15,SAUNAPOLO 56,sauna,"Rua Luciano Cordeiro, Bairro Camões, Santo Ant...",https://www.lisbongaycircuit.com/#\t,NaN,38.725931,-9.144917
16,OLISSIPO BATH,sauna,"5, Rua do Telhal, São José, Santo António, Mad...",https://www.lisbongaycircuit.com/#\t,NaN,38.719195,-9.142850
17,BISTRO EDELWEISS,restaurant,"Edelweiss, 2, Rua de São Marçal, Mercês, Santo...",https://www.lisbongaycircuit.com/#\t,NaN,38.713147,-9.151030
18,CASA DA PRAIA,restaurant,"Casa da Praia, Avenida Marginal, Junqueiro, Ca...",https://www.lisbongaycircuit.com/#\t,NaN,38.680746,-9.336876
19,DR. BERNARD,restaurant,"Dr. Bernard Boavida, 119, Rua do Poço dos Negr...",https://www.lisbongaycircuit.com/#\t,NaN,38.709787,-9.151667
20,GLITTER’S GALLERY,restaurant,"Avenida Duque de Loulé, Coração de Jesus, Sant...",https://www.lisbongaycircuit.com/#\t,NaN,38.725261,-9.148934
21,MANNY’S PLACE,restaurant,"Rua da Barroca, Bairro Alto, Misericórdia, Lis...",https://www.lisbongaycircuit.com/#\t,NaN,38.711891,-9.144530
22,MAXIME RESTAURANTE BAR,restaurant,"Maxime Hotel, 58, Praça da Alegria, São José, ...",https://www.lisbongaycircuit.com/#\t,NaN,38.718434,-9.145377
23,QUERMESSE,restaurant,"Quermesse, 85, Rua da Glória, São José, Santo ...",https://www.lisbongaycircuit.com/#\t,NaN,38.717099,-9.144691
24,TANTURA MEDITERRANEAN CUISINE,restaurant,"Tantura, 1D, Rua do Trombeta, Bairro Alto, Mis...",https://www.lisbongaycircuit.com/#\t,NaN,38.711717,-9.145115
26,HOTEL DO CHIADO,accommodation,"Hotel do Chiado, 114, Rua Nova do Almada, Chia...",https://www.lisbongaycircuit.com/#\t,NaN,38.710720,-9.139489
27,MAMA SHELTER LISBOA,accommodation,"Mama Shelter Lisboa, Rua Alexandre Herculano, ...",https://www.lisbongaycircuit.com/#\t,NaN,38.720986,-9.152422
28,HYATT REGENCY LISBOA,accommodation,"Hotel Hyatt Regency, 63, Rua da Junqueira, Alc...",https://www.lisbongaycircuit.com/#\t,NaN,38.698324,-9.186889

## Versão melhorada com sites e localizaçao pontual

Vamos obter a versão final da csv com os sites e localização pontual dos estabelecimentes

In [87]:
# pegando complete_places.csv e editando a mão para completar valores
df_final = pd.read_csv("completed_places_edited.csv")

In [88]:
import geopy.geocoders
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter
import pandas as pd
import ssl
import certifi

In [89]:
ctx = ssl.create_default_context(cafile=certifi.where())
geopy.geocoders.options.default_ssl_context = ctx
ctx = ssl.create_default_context()
ctx.check_hostname = False
ctx.verify_mode = ssl.CERT_NONE

localizer = Nominatim(scheme = 'http', user_agent="my_geolocation_places", timeout=10)
geocode = RateLimiter(localizer.geocode, min_delay_seconds=1)

In [90]:
locations = []
for i, row in df_final.iterrows():
    name = row['name']
    address = row['geolocated_address']
    location = geocode(address)
    locations.append(location)
    if location:
        print(f"-> found!: {name}")
    else:
        location = None
        print(f"-> NOT found.{name}")

print("\ngeocoding finished.")

-> found!: TRUMPS
-> found!: SOCIETY
-> found!: FRIENDS
-> found!: POSH CLUB
-> found!: CORVO
-> found!: BAR CRU
-> found!: MARIA LISBOA
-> found!: VLADA LOUNGE
-> found!: CONSTRUCTION
-> found!: FINALMENTE CLUBE
-> found!: DRAKO CLUB
-> found!: PUREX
-> found!: TR3S
-> found!: WOOFX
-> found!: BAR 106
-> found!: SHELTER
-> found!: ENTRETANTO ROOFTOP
-> found!: SIDE BAR
-> found!: XXL
-> found!: TROMBETA BATH
-> found!: SAUNAPOLO 56
-> found!: OLISSIPO BATH
-> found!: BISTRO EDELWEISS
-> found!: DR. BERNARD
-> found!: GLITTER’S GALLERY
-> found!: MANNY’S PLACE
-> found!: MAXIME RESTAURANTE BAR
-> found!: QUERMESSE
-> found!: TANTURA MEDITERRANEAN CUISINE
-> found!: HOTEL DO CHIADO
-> found!: MAMA SHELTER LISBOA
-> found!: HYATT REGENCY LISBOA
-> found!: The Late Birds Lisbon
-> found!: Browns Downtown Hotel
-> found!: Stay Inn Lisbon Hostel
-> found!: Bairro Alto Hotel
-> found!: Bairru's Bodega
-> found!: Zé dos Bois
-> found!: Moxy Lisbon City
-> found!: Margem Sul Bar
-> found!: Casa Jardim da Estrela
-> found!: Maria Caxuca
-> found!: Bar Clube da Esquina
-> found!: Mr. Woof
-> found!: UP!town Lisboa
-> found!: Lux Frágil
-> found!: Primas Bar
-> found!: Drama Bar
-> found!: Ilga Portugal
-> found!: Casa Qui
-> found!: Rede Ex Aequo
-> found!: Cinemateca Portuguesa

geocoding finished.

In [91]:
df_final['completed_address'] = [loc.address if loc else None for loc in locations]
df_final['latitude'] = [loc.latitude if loc else None for loc in locations]
df_final['longitude'] = [loc.longitude if loc else None for loc in locations]
df_final['point'] = [tuple(loc.point) if loc else None for loc in locations]

#cleaning
df_final['name'] = df_final['name'].str.upper()
df_final['name'] = df_final['name'].str.strip()
df_final['category'] = df_final['category'].astype(str).str.strip().str.lower()
df_final

,name,category,geolocated_address,ref,website,latitude,longitude,completed_address,point
0,TRUMPS,nightclub/bar,"Trumps Lisbon, 104B, Rua da Imprensa Nacional,...",https://www.timeout.pt/lisboa/pt/noite/os-melh...,https://trumps.pt/shop/,38.717415,-9.151900,"Trumps Lisbon, 104B, Rua da Imprensa Nacional,...","(38.7174149, -9.1519004, 0.0)"
1,SOCIETY,nightclub/bar,"Rua Cecílio de Sousa, 72, Mercês, Santo Antóni...",https://www.timeout.pt/lisboa/pt/noite/os-melh...,https://www.instagram.com/societylisboa/?hl=en,38.716060,-9.150158,"Rua Cecílio de Sousa, Mercês, Santo António, M...","(38.7160598, -9.1501583, 0.0)"
2,FRIENDS,nightclub/bar,"Travessa da Água-da-Flor, 17, Bairro Alto, Mis...",https://www.timeout.pt/lisboa/pt/noite/os-melh...,https://www.instagram.com/friendsbairroalto/?h...,38.713584,-9.144654,"Travessa da Água-da-Flor, Bairro Alto, Miseric...","(38.7135842, -9.1446535, 0.0)"
3,POSH CLUB,nightclub/bar,"157, Rua de São Bento, Amoreiras, Santa Isabel...",https://www.timeout.pt/lisboa/pt/noite/os-melh...,https://www.poshclublisbon.com/,38.714759,-9.154028,"157, Rua de São Bento, Amoreiras, Santa Isabel...","(38.7147594, -9.1540276, 0.0)"
4,CORVO,nightclub/bar,"Calçada Engenheiro Miguel Pais, 18, São Mamede...",https://www.timeout.pt/lisboa/pt/noite/os-melh...,(fechou)https://www.instagram.com/corvo_princi...,38.717143,-9.151472,"Calçada Engenheiro Miguel Pais, São Mamede, Sa...","(38.7171429, -9.1514721, 0.0)"
5,BAR CRU,nightclub/bar,"Bar Cru, 170, Rua de São Marçal, Mercês, Santo...",https://www.timeout.pt/lisboa/pt/noite/os-melh...,https://thebarcru.com/,38.715988,-9.150327,"Bar Cru, 170, Rua de São Marçal, Mercês, Santo...","(38.7159879, -9.1503266, 0.0)"
6,MARIA LISBOA,nightclub/bar,"Rua da Atalaia, 97, Bairro Alto, Misericórdia,...",https://www.timeout.pt/lisboa/pt/noite/os-melh...,https://www.facebook.com/MariaLisboaClub/,38.712770,-9.145033,"Rua da Atalaia, Bairro Alto, Misericórdia, Lis...","(38.7127697, -9.1450332, 0.0)"
7,VLADA LOUNGE,nightclub/bar,"8, Rua Rosa Damasceno, Arroios, Lisboa, 1900-9...",https://www.timeout.pt/lisboa/pt/noite/os-melh...,https://www.instagram.com/vladalounge/?hl=en,38.735957,-9.131970,"8, Rua Rosa Damasceno, Arroios, Lisboa, 1900-9...","(38.7359566, -9.1319704, 0.0)"
8,CONSTRUCTION,nightclub/bar,"RUA CECILIO DE SOUSA, 82, Lisboa, Portugal",https://www.timeout.pt/lisboa/pt/noite/os-melh...,https://www.instagram.com/construction_bar/?hl=en,38.716060,-9.150158,"Rua Cecílio de Sousa, Mercês, Santo António, M...","(38.7160598, -9.1501583, 0.0)"
9,FINALMENTE CLUBE,nightclub/bar,"Finalmente Clube, 38, Rua da Palmeira, Mercês,...",https://www.timeout.pt/lisboa/pt/noite/os-melh...,https://www.finalmenteclub.com/,38.714790,-9.149876,"Finalmente Clube, 38, Rua da Palmeira, Mercês,...","(38.7147899, -9.1498756, 0.0)"
10,DRAKO CLUB,nightclub/bar,"11, Rua Nogueira e Sousa, Bairro Camões, Santo...",https://www.timeout.pt/lisboa/pt/noite/os-melh...,https://www.drako.club/,38.723453,-9.143187,"11, Rua Nogueira e Sousa, Bairro Camões, Santo...","(38.7234529, -9.1431873, 0.0)"
11,PUREX,nightclub/bar,"28, Rua das Salgadeiras, Bairro Alto, Misericó...",https://www.timeout.pt/lisboa/pt/noite/os-melh...,https://www.instagram.com/purexclube/,38.710973,-9.144427,"28, Rua das Salgadeiras, Bairro Alto, Misericó...","(38.7109727, -9.144427, 0.0)"
12,TR3S,nightclub/bar,"TR3S Lisboa, 2, Rua Ruben A. Leitão, Mercês, M...",https://www.timeout.pt/lisboa/pt/noite/os-melh...,https://www.tr3slisboa.com/,38.714329,-9.149425,"TR3S Lisboa, 2, Rua Ruben A. Leitão, Mercês, M...","(38.714329, -9.1494246, 0.0)"
13,WOOFX,nightclub/bar,"woof x Lisbon, 2 B, Rua Manuel Bernardes, Merc...",https://www.timeout.pt/lisboa/pt/noite/os-melh...,https://www.instagram.com/woofx.2b/,38.714739,-9.152072,"woof x Lisbon, 2 B, Rua Manuel Bernardes, Merc...","(38.7147389, -9.1520719, 0.0)"
14,BAR 106,nightclub/bar,"Rua de São Marçal, 106, Mercês, Santo António,...",https://www.timeout.pt/lisboa/pt/noite/os-melh...,https://www.instagram.com/bar106lx/?hl=en,38.715174,-9.150707,"96 - 106, Rua de São Marçal, Mercês, Santo Ant...","(38.7151744, -9.1507073, 0.0)"
15,SHELTER,nightclub/bar,"43, Rua da Palmeira, Mercês, Misericórdia, Lis...",https://www.timeout.pt/lisboa/pt/noite/os-melh...,https://www.shelterbarlisboa.com/,38.714861,-9.150507,"43, Rua da Palmeira, Mercês, Misericórdia, Lis...","(38.7148612, -9.1505072, 0.0)"
16,ENTRETANTO ROOFTOP,nightclub/bar,"Hotel do Chiado, 114, Rua Nova do Almada, Chia...",https://www.lisbongaycircuit.com/#,https://www.hoteldochiado.pt/,38.710720,-9.139489,"Hotel do Chiado, 114, Rua Nova do Almada, Chia...","(38.7107197, -9.1394885, 0.0)"
17,SIDE BAR,nightclub/bar,"Rua da Barroca 33, Lisboa, 1200-050, Portugal",https://www.lisbongaycircuit.com/#,https://www.instagram.com/sidebar_bairroalto/?...,38.711896,-9.144542,"Rua da Barroca, Bairro Alto, Misericórdia, Lis...","(38.7118961, -9.1445422, 0.0)"
18,XXL,nightclub/bar,"Calçada do Tijolo, 8 - 1200-408, Bairro Alto, ...",https://www.lisbongaycircuit.com/#,https://www.instagram.com/xxllisbon/?hl=en,38.714244,-9.146118,"Calçada do Tijolo, Bairro Alto, Misericórdia, ...","(38.7142437, -9.1461183, 0.0)"
19,TROMBETA BATH,sauna,"Trombeta Bath (men only), 1C, Rua do Trombeta,...",https://www.lisbongaycircuit.com/#,https://www.trombetabath.com/,38.711585,-9.145157,"Trombeta Bath (men only), 1C, Rua do Trombeta,...","(38.7115849, -9.1451568, 0.0)"
20,SAUNAPOLO 56,sauna,"Rua Luciano Cordeiro,56A, Bairro Camões, Santo...",https://www.lisbongaycircuit.com/#,https://www.saunapolo56.pt/,38.725931,-9.144917,"Rua Luciano Cordeiro, Bairro Camões, Santo Ant...","(38.7259314, -9.144917, 0.0)"
21,OLISSIPO BATH,sauna,"5, Rua do Telhal, São José, Santo António, Mad...",https://www.lisbongaycircuit.com/#,https://www.instagram.com/olissiposauna/?hl=en,38.719195,-9.142850,"5, Rua do Telhal, São José, Santo António, Mad...","(38.7191952, -9.1428501, 0.0)"
22,BISTRO EDELWEISS,restaurant,"Edelweiss, 2, Rua de São Marçal, Mercês, Santo...",https://www.lisbongaycircuit.com/#,https://bistroedelweiss.eatbu.com/?lang=pt,38.713147,-9.151030,"Edelweiss, 2, Rua de São Marçal, Mercês, Santo...","(38.7131474, -9.1510302, 0.0)"
23,DR. BERNARD,restaurant,"Dr. Bernard Boavida, 119, Rua do Poço dos Negr...",https://www.lisbongaycircuit.com/#,https://www.instagram.com/boavidadrbernard/?hl=en,38.709787,-9.151667,"Dr. Bernard Boavida, 119, Rua do Poço dos Negr...","(38.7097868, -9.1516671, 0.0)"
24,GLITTER’S GALLERY,restaurant,"Avenida Duque de Loulé, 51B, Coração de Jesus,...",https://www.lisbongaycircuit.com/#,https://www.instagram.com/glitters_lisboa/?hl=en,38.725261,-9.148934,"Avenida Duque de Loulé, Coração de Jesus, Sant...","(38.7252609, -9.1489343, 0.0)"
25,MANNY’S PLACE,restaurant,"Rua da Barroca,92, Bairro Alto, Misericórdia, ...",https://www.lisbongaycircuit.com/#,https://www.mannysplacelisbon.com/,38.711896,-9.144542,"Rua da Barroca, Bairro Alto, Misericórdia, Lis...","(38.7118961, -9.1445422, 0.0)"
26,MAXIME RESTAURANTE BAR,restaurant,"Maxime Hotel, 58, Praça da Alegria, São José, ...",https://www.lisbongaycircuit.com/#,https://www.maximerestaurantelisboa.com/,38.718434,-9.145377,"Maxime Hotel, 58, Praça da Alegria, São José, ...","(38.718434, -9.1453769, 0.0)"
27,QUERMESSE,restaurant,"Quermesse, 85, Rua da Glória, São José, Santo ...",https://www.lisbongaycircuit.com/#,https://www.instagram.com/quermesse.restaurant...,38.717099,-9.144691,"Quermesse, 85, Rua da Glória, São José, Santo ...","(38.7170987, -9.1446908, 0.0)"
28,TANTURA MEDITERRANEAN CUISINE,restaurant,"Tantura, 1D, Rua do Trombeta, Bairro Alto, Mis...",https://www.lisbongaycircuit.com/#,https://tantura.pt/,38.711717,-9.145115,"Tantura, 1D, Rua do Trombeta, Bairro Alto, Mis...","(38.7117173, -9.1451152, 0.0)"
29,HOTEL DO CHIADO,accommodation,"Hotel do Chiado, 114, Rua Nova do Almada, Chia...",https://www.lisbongaycircuit.com/#,https://www.hoteldochiado.pt/,38.710720,-9.139489,"Hotel do Chiado, 114, Rua Nova do Almada, Chia...","(38.7107197, -9.1394885, 0.0)"
30,MAMA SHELTER LISBOA,accommodation,"Mama Shelter Lisboa, Rua Alexandre Herculano, ...",https://www.lisbongaycircuit.com/#,https://pt.mamashelter.com/lisboa/,38.720986,-9.152422,"Mama Shelter Lisboa, Rua Alexandre Herculano, ...","(38.7209863, -9.1524216, 0.0)"
31,HYATT REGENCY LISBOA,accommodation,"Hotel Hyatt Regency, 63, Rua da Junqueira, Alc...",https://www.lisbongaycircuit.com/#,https://www.hyatt.com/hyatt-regency/pt-PT/lish...,38.698324,-9.186889,"Hotel Hyatt Regency, 63, Rua da Junqueira, Alc...","(38.698324, -9.1868891, 0.0)"
32,THE LATE BIRDS LISBON,accommodation,"Travessa André Valente 21, Lisboa, Portugal",https://www.hotelandia.pt/hoteis-gay-friendly-...,https://www.thelatebirdslisbon.com/,38.711419,-9.147588,"Travessa André Valente, Santa Catarina, Miseri...","(38.7114185, -9.1475878, 0.0)"
33,BROWNS DOWNTOWN HOTEL,accommodation,"Rua dos Sapateiros 73, Lisboa, Portugal",https://www.hotelandia.pt/hoteis-gay-friendly-...,https://www.brownshotelgroup.com/en/browns-dow...,38.711165,-9.138312,"Rua dos Sapateiros, Santa Maria Maior, Madalen...","(38.7111648, -9.1383122, 0.0)"
34,STAY INN LISBON HOSTEL,accommodation,"Rua Luz Soriano, 19, Lisboa, Portugal",https://www.hotelandia.pt/hoteis-gay-friendly-...,https://stayinnhostel.hotelsoflisbon.com/en/,38.711266,-9.145942,"19, Rua Luz Soriano, Bairro Alto, Misericórdia...","(38.7112659, -9.1459416, 0.0)"
35,BAIRRO ALTO HOTEL,accommodation,Bairro Alto Hotel,https://www.hotelandia.pt/hoteis-gay-friendly-...,https://www.bairroaltohotel.com/pt/,38.710274,-9.143284,"Bairro Alto Hotel, 2, Praça Luís de Camões, En...","(38.7102737, -9.1432838, 0.0)"
36,BAIRRU'S BODEGA,nightclub/bar,"Rua da Barroca, 3, Bairro Alto, Lisboa, Portugal",https://www.lisbonlux.com/lisboa/turismo/gay-l...,https://www.facebook.com/people/Bairrus-Bodega...,38.711896,-9.144542,"Rua da Barroca, Bairro Alto, Misericórdia, Lis...","(38.7118961, -9.1445422, 0.0)"
37,ZÉ DOS BOIS,cultural space,"Rua da Barroca 59, 1200-049 Lisboa, Portugal",https://www.contiki.com/six-two/article/lgbtqi...,https://zedosbois.org/,38.711765,-9.144561,"Zé dos Bois, 59, Rua da Barroca, Bairro Alto, ...","(38.7117647, -9.1445614, 0.0)"
38,MOXY LISBON CITY,accommodation,Moxy Lisbon City,https://www.kayak.com.br/news/gay-lisboa/,https://www.instagram.com/moxylisboncity/?hl=en,38.729166,-9.144120,"Moxy Lisbon City, 2, Avenida Duque de Loulé, S...","(38.7291658, -9.1441198, 0.0)"
39,MARGEM SUL BAR,nightclub/bar,"Rua da Liberdade, 11, Lisboa, Portugal",https://europride2025.pt/events/,https://www.instagram.com/margem_sul_club_bar/...,38.784505,-9.345944,"11, Rua da Liberdade, São Carlos, Mem Martins,...","(38.7845054, -9.3459438, 0.0)"
40,CASA JARDIM DA ESTRELA,cultural space,"Jardim da Estrela, 1200-694 Lisboa, Portugal",https://europride2025.pt/events/,https://www.instagram.com/casadojardimdaestrel...,38.715777,-9.159556,"Jardim da Estrela, Rua de São Jorge, Santa Isa...","(38.7157774, -9.1595563, 0.0)"
41,MARIA CAXUCA,nightclub/bar,"Rua da Barroca, 12, Lisbon, Portugal",Google Recommendation,https://www.instagram.com/mariacaxuxabar/?hl=en,38.711163,-9.144436,"Maria Caxuxa, 6-12, Rua da Barroca, Bairro Alt...","(38.7111633, -9.1444355, 0.0)"
42,BAR CLUBE DA ESQUINA,nightclub/bar,"Rua da Barroca, 30, Lisbon, Portugal",https://dicadeportugal.com/diversao/bares-gay-...,https://www.instagram.com/clubedaesquina/?hl=en,38.711482,-9.144434,"Clube da Esquina, 30, Rua da Barroca, Bairro A...","(38.7114821, -9.1444344, 0.0)"
43,MR. WOOF,store,"Rua Ruben A. Leitão 23, Lisboa, Portugal",https://www.misterbandb.com/pt/gay-guide/portu...,https://www.facebook.com/Mr.Woof.Store/,38.714405,-9.149769,"Rua Ruben A. Leitão, Mercês, Misericórdia, Lis...","(38.7144047, -9.1497689, 0.0)"
44,UP!TOWN LISBOA,store,"R. da Misericórdia, 68, Lisboa, Portugal",https://www.misterbandb.com/pt/gay-guide/portu...,https://www.facebook.com/uptownlisboa/,38.711933,-9.142961,"Rua da Misericórdia, Encarnação, Misericórdia,...","(38.7119328, -9.1429612, 0.0)"
45,LUX FRÁGIL,nightclub/bar,"Avenida Infante Dom Henrique, Lisboa, Portugal",https://wikinight.eu/pt/comunidade/as-melhores...,https://www.luxfragil.com/,38.714412,-9.121701,"Avenida Infante Dom Henrique, São Vicente de F...","(38.7144118, -9.1217011, 0.0)"
46,PRIMAS BAR,nightclub/bar,"Rua da Atalaia, 154, Lisboa, Portugal",Google,https://www.facebook.com/p/Primas-Bar-10005755...,38.712770,-9.145033,"Rua da Atalaia, Bairro Alto, Misericórdia, Lis...","(38.7127697, -9.1450332, 0.0)"
47,DRAMA BAR,nightclub/bar,"Rua Damasceno Monteiro 75, Lisboa Portugal",NaN,https://www.instagram.com/dramabar.lisboa/?hl=en,38.721302,-9.131861,"75, Rua Damasceno Monteiro, Anjos, Arroios, Li...","(38.7213015, -9.1318612, 0.0)"
48,ILGA PORTUGAL,association,"Rua dos Fanqueiros,40, Lisboa, Portugal",NaN,https://ilga-portugal.pt/,38.709807,-9.135549,"Rua dos Fanqueiros, Santa Maria Maior, Madalen...","(38.7098067, -9.1355489, 0.0)"
49,CASA QUI,association,"Largo das Conchas 1,Lisboa, Portugal",NaN,https://www.casa-qui.pt/,38.767959,-9.157455,"Largo das Conchas, Quinta do Lambert, Lumiar, ...","(38.7679587, -9.1574553, 0.0)"
50,REDE EX AEQUO,association,"Rua dos Fanqueiros, 38, Lisboa, Portugal",NaN,https://rea.pt/,38.709807,-9.135549,"Rua dos Fanqueiros, Santa Maria Maior, Madalen...","(38.7098067, -9.1355489, 0.0)"
51,CINEMATECA PORTUGUESA,cultural space,"Rua Barata Salgueiro, 39, Lisboa, Portugal",NaN,https://www.cinemateca.pt/,38.720771,-9.148647,"Cinemateca Portuguesa - Museu do Cinema, 39, R...","(38.7207707, -9.1486475, 0.0)"

In [92]:
df_final.to_csv('final_places.csv', index=False, encoding='utf-8-sig')

# Plotando em um mapa usando Folium

https://getbootstrap.com/docs/3.3/components/

https://fontawesome.com/v4/icons/

In [127]:
categories_config = {
    'nightclub/bar': {'color': 'pink', 'icon':'glyphicon glyphicon-glass' , 'prefix': 'glyphicon'},       
    'sauna': {'color':'darkred', 'icon':'fa-bath', 'prefix': 'fa'},              
    'restaurant': {'color':'orange', 'icon':'glyphicon glyphicon-cutlery' , 'prefix': 'glyphicon'},        
    'association': {'color':'purple', 'icon':'glyphicon glyphicon-heart-empty' , 'prefix': 'glyphicon'},      
    'accommodation': {'color':'green', 'icon':'fa-bed', 'prefix': 'fa'},    
    'cultural space': {'color':'gray', 'icon':'film' , 'prefix': 'glyphicon'},  
    'store': {'color':'lightblue', 'icon':'glyphicon glyphicon-shopping-cart' , 'prefix': 'glyphicon'}, #or glyphicon glyphicon-tag
    }

In [172]:
subtitle_html = """
<div style="
    position: fixed;
    bottom: 20px;
    right: 20px;
    z-index: 1000;
    background: white;
    padding: 10px;
    border: 1px solid gray;
    opacity: 0.9;
    font-family: Arial;
    max-height: 200px;
    overflow-y: auto;
">
    <b>Subtitle</b>
"""
for name, config in categories_config.items():
    subtitle_html += f"""
    <div style="margin: 5px 0;">
        <span style="color: {config['color']}; font-size: 18px;">■</span>
        {name}
    </div>
    """

subtitle_html += "</div>"

subtitle = Element(subtitle_html)

In [176]:
default_color = 'black'
center = [38.7223, -9.1393]
lisbon_map = folium.Map(location=center, zoom_start=14)
lisbon_map.get_root().html.add_child(subtitle)

Geocoder().add_to(lisbon_map)

for i, row in df_final.iterrows():
    if pd.notna(row['latitude']) and pd.notna(row['longitude']):
        coordinates = [row['latitude'], row['longitude']]
        name = row['name']
        address = row['completed_address']
        category = row['category']
        site = row['website']
            
        icon_config = categories_config.get(category, {
                                             'color': default_color,
                                             'icon': 'glyphicon glyphicon-remove',
                                             'prefix': 'glyphicon'
                                            })
        html_popup = f"""
        <h4>{name}</h4>
        <p>
        <b>Address: </b> {address}<br>
        </p>
        <p>
        <b>Category: </b> {category}<br>
        </p>
        <p>
        <b>Site: </b> {site}<br>
        </p>
        """
        popup = folium.Popup(html_popup, max_width=250)
        folium.Marker(
            location=coordinates,
            popup=popup, 
            tooltip=name, 
            icon=folium.Icon(
                icon = icon_config['icon'],
                color= icon_config['color'],
                prefix= icon_config['prefix'],
                icon_color='white'
                ) ).add_to(lisbon_map)

lisbon_map.save('lisbon_places_map.html')
lisbon_map